"""Add description to MeetingRoom

Revision ID: 9a31e6c118ae
Revises: b7f95d7fe950
Create Date: 2024-07-05 01:38:11.183489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a31e6c118ae'
down_revision = 'b7f95d7fe950'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetingroom', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetingroom', 'description')
    # ### end Alembic commands ###
